# Generated by Django 5.2.13 on 2026-05-11 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('AMBOS', 'Ambos')], default='EGRESO', max_length=20)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría financiera',
                'verbose_name_plural': 'Categorías financieras',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.categoriafinanciera'),
        ),
    ]
