# Generated by Django 5.2.13 on 2026-08-19 02:06

import django.utils.timezone
from django.db import migrations, models


def crear_categorias_no_operacionales(apps, schema_editor):
    Categoria = apps.get_model('finanzas', 'CategoriaFinanciera')
    for nombre, tipo, descripcion in (
        ('DONACIONES Y APORTES', 'INGRESO', 'Donaciones, aportes voluntarios y patrocinios sin contraprestación.'),
        ('OTROS INGRESOS NO OPERACIONALES', 'INGRESO', 'Ingresos extraordinarios diferentes a mensualidades y servicios.'),
        ('OTROS GASTOS NO OPERACIONALES', 'EGRESO', 'Gastos extraordinarios ajenos a la operación habitual.'),
    ):
        Categoria.objects.get_or_create(
            nombre=nombre,
            defaults={
                'tipo': tipo,
                'naturaleza': 'NO_OPERACIONAL',
                'descripcion': descripcion,
                'activa': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_movimientofinanciero_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriafinanciera',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='categoriafinanciera',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='categoriafinanciera',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='categoriafinanciera',
            name='naturaleza',
            field=models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('NO_OPERACIONAL', 'No operacional')], default='OPERACIONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='soporte',
            field=models.FileField(blank=True, help_text='Factura, recibo, comprobante, imagen o PDF relacionado.', null=True, upload_to='finanzas/academia/soportes/%Y/%m/'),
        ),
    ]
