# Generated by Django 5.2.13 on 2026-05-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_promo_url', models.URLField(blank=True, null=True, verbose_name='URL video promo YouTube')),
                ('playlist_youtube_url', models.URLField(blank=True, null=True, verbose_name='URL playlist YouTube')),
                ('activo', models.BooleanField(default=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Home',
                'verbose_name_plural': 'Configuración Home',
            },
        ),
    ]
