# Generated by Django 5.2.13 on 2026-06-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_antes_vencimiento', models.PositiveIntegerField(default=5)),
                ('enviar_correo', models.BooleanField(default=True)),
                ('mensaje_vencimiento', models.TextField(default='Tu suscripción está próxima a vencer. Por favor realiza tu renovación para continuar entrenando.')),
                ('activo', models.BooleanField(default=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de notificación',
                'verbose_name_plural': 'Configuración de notificaciones',
            },
        ),
    ]
