# Generated by Django 5.2.13 on 2026-06-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_configuracionnotificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='HoraHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(unique=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'hora'],
            },
        ),
    ]
