# Generated by Django 5.2.13 on 2026-06-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_diahorario_horahorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionhome',
            name='video_promo_archivo',
            field=models.FileField(blank=True, null=True, upload_to='videos_home/', verbose_name='Video promo MP4'),
        ),
    ]
