# Generated by Django 5.2.13 on 2026-08-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_sesiontv'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionhome',
            name='orden_video_promocional',
            field=models.PositiveIntegerField(default=10, help_text='Los números menores aparecen primero. Por ejemplo, un seminario con prioridad 5 se mostrará antes de un video con prioridad 10.', verbose_name='Prioridad del video promocional'),
        ),
    ]
