# Generated by Django 5.2.13 on 2026-08-05 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_normalizar_nombres_propios'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionClases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_antes_confirmacion', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(180)], verbose_name='Minutos antes de la clase')),
                ('minutos_despues_confirmacion', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(180)], verbose_name='Minutos después de iniciar')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de clases',
                'verbose_name_plural': 'Configuración de clases',
            },
        ),
    ]
