# Generated by Django 5.2.13 on 2026-08-14 13:55

import django.core.validators
from django.db import migrations, models


def ampliar_ventana_predeterminada(apps, schema_editor):
    ConfiguracionClases = apps.get_model('gestion', 'ConfiguracionClases')
    ConfiguracionClases.objects.filter(
        minutos_antes_confirmacion=30
    ).update(minutos_antes_confirmacion=60)


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_configuracion_ventana_clases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionclases',
            name='minutos_antes_confirmacion',
            field=models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(180)], verbose_name='Minutos antes de la clase'),
        ),
        migrations.RunPython(
            ampliar_ventana_predeterminada,
            migrations.RunPython.noop,
        ),
    ]
