# Generated by Django 5.2.13 on 2026-09-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_ventana_confirmacion_una_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionhome',
            name='orden_publicidad_tienda',
            field=models.PositiveIntegerField(default=8, help_text='Los números menores aparecen primero en el carrusel.', verbose_name='Prioridad de la publicidad de tienda'),
        ),
        migrations.AddField(
            model_name='configuracionhome',
            name='publicidad_tienda_activa',
            field=models.BooleanField(default=False, verbose_name='Mostrar publicidad de la tienda'),
        ),
        migrations.AddField(
            model_name='configuracionhome',
            name='publicidad_tienda_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tienda/publicidad/', verbose_name='Imagen publicitaria de la tienda'),
        ),
        migrations.AddField(
            model_name='configuracionhome',
            name='publicidad_tienda_texto',
            field=models.CharField(blank=True, default='Conoce nuestras prendas, equipos y productos deportivos.', max_length=240),
        ),
        migrations.AddField(
            model_name='configuracionhome',
            name='publicidad_tienda_titulo',
            field=models.CharField(default='Tienda Bross Fight Sports', max_length=120),
        ),
    ]
