# Generated by Django 5.2.13 on 2026-10-02 22:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_billeteras_iniciales(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    Usuario = apps.get_model(app_label, model_name)
    Billetera = apps.get_model('gestion', 'BilleteraMonedas')
    Billetera.objects.bulk_create(
        [Billetera(usuario_id=usuario_id) for usuario_id in Usuario.objects.values_list('id', flat=True)]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0007_asistencia_instructores'),
        ('gestion', '0010_configuracionhome_orden_publicidad_tienda_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionclases',
            name='gamificacion_activa',
            field=models.BooleanField(default=True, verbose_name='Entregar monedas por asistencia'),
        ),
        migrations.AddField(
            model_name='configuracionclases',
            name='monedas_por_asistencia',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Monedas por asistencia'),
        ),
        migrations.CreateModel(
            name='BilleteraMonedas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.PositiveIntegerField(default=0)),
                ('avatar', models.CharField(choices=[('HUEVO', 'Huevo inicial')], default='HUEVO', max_length=20)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billetera_monedas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billetera de monedas',
                'verbose_name_plural': 'Billeteras de monedas',
            },
        ),
        migrations.RunPython(crear_billeteras_iniciales, migrations.RunPython.noop),
        migrations.CreateModel(
            name='MovimientoMonedas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ASISTENCIA', 'Premio por asistencia'), ('AJUSTE', 'Ajuste administrativo'), ('DESCUENTO', 'Descuento de monedas')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('saldo_resultante', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=220)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('asistencia', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='premio_monedas', to='clases.asistenciaclase')),
                ('billetera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='gestion.billeteramonedas')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_monedas_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de monedas',
                'verbose_name_plural': 'Movimientos de monedas',
                'ordering': ['-creado', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad', 0), _negated=True), name='movimiento_monedas_cantidad_no_cero')],
            },
        ),
    ]
