# Generated by Django 5.2.13 on 2026-10-07 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_estrella_inicial(apps, schema_editor):
    TipoRecompensa = apps.get_model('gestion', 'TipoRecompensa')
    TipoRecompensa.objects.get_or_create(
        nombre='Estrella',
        defaults={
            'simbolo': '⭐',
            'valor_monedas': 5,
            'cantidad_para_bono': 5,
            'monedas_bono': 5,
            'activa': True,
            'orden': 1,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_alumno_permitir_asistencia_vencida'),
        ('clases', '0007_asistencia_instructores'),
        ('gestion', '0011_configuracionclases_gamificacion_activa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRecompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('simbolo', models.CharField(default='⭐', help_text='Emoji o símbolo corto que se mostrará junto al estudiante.', max_length=12)),
                ('imagen', models.ImageField(blank=True, help_text='Opcional. Si se carga, reemplaza el símbolo en la pantalla.', null=True, upload_to='recompensas/')),
                ('valor_monedas', models.PositiveIntegerField(default=5)),
                ('cantidad_para_bono', models.PositiveSmallIntegerField(default=0, help_text='Cantidad que completa un ciclo. Usa 0 para no crear ciclos.')),
                ('monedas_bono', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de recompensa',
                'verbose_name_plural': 'Tipos de recompensas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RunPython(crear_estrella_inicial, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='movimientomonedas',
            name='tipo',
            field=models.CharField(choices=[('ASISTENCIA', 'Premio por asistencia'), ('RECOMPENSA', 'Recompensa del profesor'), ('BONO_RECOMPENSA', 'Bono por recompensas acumuladas'), ('AJUSTE', 'Ajuste administrativo'), ('DESCUENTO', 'Descuento de monedas')], max_length=20),
        ),
        migrations.CreateModel(
            name='RecompensaOtorgada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_snapshot', models.CharField(max_length=80)),
                ('simbolo_snapshot', models.CharField(blank=True, max_length=12)),
                ('imagen_snapshot', models.CharField(blank=True, max_length=255)),
                ('monedas_otorgadas', models.PositiveIntegerField(default=0)),
                ('bono_otorgado', models.PositiveIntegerField(default=0)),
                ('motivo', models.CharField(blank=True, max_length=180)),
                ('canjeada', models.BooleanField(default=False)),
                ('canjeada_en', models.DateTimeField(blank=True, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recompensas_recibidas', to='alumnos.alumno')),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recompensas_otorgadas', to='clases.asistenciaclase')),
                ('otorgada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recompensas_otorgadas', to=settings.AUTH_USER_MODEL)),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='gestion.tiporecompensa')),
            ],
            options={
                'verbose_name': 'Recompensa otorgada',
                'verbose_name_plural': 'Recompensas otorgadas',
                'ordering': ['-creada', '-id'],
            },
        ),
        migrations.AddField(
            model_name='movimientomonedas',
            name='recompensa_otorgada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_monedas', to='gestion.recompensaotorgada'),
        ),
        migrations.AddConstraint(
            model_name='recompensaotorgada',
            constraint=models.UniqueConstraint(fields=('recompensa', 'asistencia'), name='recompensa_unica_por_tipo_y_asistencia'),
        ),
    ]
