# Generated by Django 5.2.13 on 2026-10-08 01:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_recompensas_configurables'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionclases',
            name='monedas_por_asistencia_profesor',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Monedas por clase para profesores'),
        ),
        migrations.AlterField(
            model_name='movimientomonedas',
            name='tipo',
            field=models.CharField(choices=[('ASISTENCIA', 'Premio por asistencia'), ('ASISTENCIA_PROF', 'Premio por asistencia de profesor'), ('RECOMPENSA', 'Recompensa del profesor'), ('BONO_RECOMPENSA', 'Bono por recompensas acumuladas'), ('AJUSTE', 'Ajuste administrativo'), ('DESCUENTO', 'Descuento de monedas')], max_length=20),
        ),
    ]
