from django.urls import path

from . import views


app_name = 'tienda'

urlpatterns = [
    path('catalogo/', views.catalogo, name='catalogo'),
    path('catalogo/sugerencias/', views.sugerencias_catalogo, name='sugerencias_catalogo'),
    path('catalogo/agregar/<int:producto_id>/', views.agregar_carrito, name='agregar_carrito'),
    path('catalogo/carrito/', views.carrito, name='carrito'),
    path('catalogo/carrito/actualizar/', views.actualizar_carrito, name='actualizar_carrito'),
    path('catalogo/carrito/eliminar/<int:producto_id>/', views.eliminar_del_carrito, name='eliminar_del_carrito'),
    path('catalogo/finalizar/', views.finalizar_pedido, name='finalizar_pedido'),
    path('catalogo/pedido/<int:pedido_id>/confirmado/', views.pedido_confirmado, name='pedido_confirmado'),
    path('', views.panel, name='panel'),
    path('configuracion/', views.configuracion, name='configuracion'),
    path('pedidos/', views.pedidos_publicos, name='pedidos'),
    path('pedidos/<int:pedido_id>/decidir/', views.decidir_pedido, name='decidir_pedido'),
    path('pedidos/<int:pedido_id>/estado/', views.actualizar_estado_pedido, name='actualizar_estado_pedido'),
    path('cuentas/nueva/', views.cuenta, name='crear_cuenta'),
    path('cuentas/<int:cuenta_id>/editar/', views.cuenta, name='editar_cuenta'),
    path('cuentas/<int:cuenta_id>/estado/', views.cambiar_estado_cuenta, name='cambiar_estado_cuenta'),
    path('categorias/nueva/', views.categoria, name='crear_categoria'),
    path('categorias/<int:categoria_id>/editar/', views.categoria, name='editar_categoria'),
    path('categorias-contables/nueva/', views.categoria_contable, name='crear_categoria_contable'),
    path('categorias-contables/<int:categoria_id>/editar/', views.categoria_contable, name='editar_categoria_contable'),
    path('subcategorias/nueva/', views.subcategoria, name='crear_subcategoria'),
    path('subcategorias/<int:subcategoria_id>/editar/', views.subcategoria, name='editar_subcategoria'),
    path('marcas/nueva/', views.marca_producto, name='crear_marca'),
    path('marcas/<int:marca_id>/editar/', views.marca_producto, name='editar_marca'),
    path('lineas-modelos/nueva/', views.linea_modelo_producto, name='crear_linea_modelo'),
    path('lineas-modelos/<int:linea_id>/editar/', views.linea_modelo_producto, name='editar_linea_modelo'),
    path('catalogos/lineas-modelos/', views.lineas_modelos_por_marca, name='lineas_modelos_por_marca'),
    path('catalogos/subcategorias/', views.subcategorias_por_categoria, name='subcategorias_por_categoria'),
    path('disciplinas-producto/nueva/', views.disciplina_producto, name='crear_disciplina_producto'),
    path('disciplinas-producto/<int:disciplina_id>/editar/', views.disciplina_producto, name='editar_disciplina_producto'),
    path('proveedores/nuevo/', views.proveedor_tienda, name='crear_proveedor'),
    path('proveedores/<int:proveedor_id>/editar/', views.proveedor_tienda, name='editar_proveedor'),
    path('clientes/nuevo/', views.cliente, name='crear_cliente'),
    path('clientes/<int:cliente_id>/editar/', views.cliente, name='editar_cliente'),
    path('productos/nuevo/', views.producto, name='crear_producto'),
    path('productos/<int:producto_id>/editar/', views.producto, name='editar_producto'),
    path(
        'productos/<int:producto_id>/estado/',
        views.cambiar_estado_producto,
        name='cambiar_estado_producto',
    ),
    path('ventas/nueva/', views.registrar_venta, name='registrar_venta'),
    path('ventas/<int:venta_id>/', views.detalle_venta, name='detalle_venta'),
    path('ventas/<int:venta_id>/comprobante.pdf', views.descargar_comprobante, name='descargar_comprobante'),
    path('ventas/<int:venta_id>/enviar-correo/', views.enviar_comprobante_correo, name='enviar_comprobante_correo'),
    path('ventas/<int:venta_id>/abono/', views.registrar_abono, name='registrar_abono'),
    path('ventas/<int:venta_id>/paz-y-salvo/', views.paz_y_salvo, name='paz_y_salvo'),
    path('ventas/<int:venta_id>/entregar/', views.marcar_venta_entregada, name='marcar_venta_entregada'),
    path('creditos/', views.creditos, name='creditos'),
    path(
        'creditos/cartera-inicial/nueva/',
        views.registrar_cartera_inicial,
        name='registrar_cartera_inicial',
    ),
    path('compras/nueva/', views.registrar_compra, name='registrar_compra'),
    path('compras/credito/', views.compras_credito, name='compras_credito'),
    path('compras/<int:compra_id>/abono/', views.registrar_abono_compra, name='registrar_abono_compra'),
    path('gastos/nuevo/', views.registrar_gasto, name='registrar_gasto'),
    path('ingresos/nuevo/', views.registrar_ingreso, name='registrar_ingreso'),
    path('transferencias/nueva/', views.registrar_transferencia, name='registrar_transferencia'),
    path('inventario/ajustar/', views.ajustar_inventario, name='ajustar_inventario'),
    path('consultas/', views.consultas, name='consultas'),
]
