# Generated by Django 5.2.13 on 2026-05-06 22:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0002_asistenciaclase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimientoFirmado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADULTO', 'Adulto'), ('MENOR', 'Menor de edad')], max_length=20)),
                ('nombre_estudiante', models.CharField(max_length=150)),
                ('documento_estudiante', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_acudiente', models.CharField(blank=True, max_length=150, null=True)),
                ('documento_acudiente', models.CharField(blank=True, max_length=30, null=True)),
                ('texto_aceptado', models.TextField()),
                ('firma_base64', models.TextField()),
                ('fecha_firma', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ClaseCortesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('edad', models.PositiveIntegerField()),
                ('tipo_persona', models.CharField(choices=[('ADULTO', 'Adulto'), ('MENOR', 'Menor de edad')], max_length=20)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortesias', to='clases.claseprogramada')),
                ('consentimiento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='clase_cortesia', to='cortesias.consentimientofirmado')),
            ],
        ),
    ]
