# Generated by Django 5.2.13 on 2026-05-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortesias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasecortesia',
            name='condicion_medica',
            field=models.TextField(blank=True, null=True, verbose_name='Discapacidad, lesión o enfermedad importante'),
        ),
        migrations.AddField(
            model_name='clasecortesia',
            name='documento_acudiente',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='clasecortesia',
            name='eps',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clasecortesia',
            name='nombre_acudiente',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clasecortesia',
            name='parentesco_acudiente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clasecortesia',
            name='telefono_acudiente',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
