# Generated by Django 5.2.13 on 2026-06-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortesias', '0002_clasecortesia_condicion_medica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasecortesia',
            name='contactado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clasecortesia',
            name='fecha_contacto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clasecortesia',
            name='observacion_seguimiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clasecortesia',
            name='se_convirtio',
            field=models.BooleanField(default=False),
        ),
    ]
