# Generated by Django 5.2.13 on 2026-08-05 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0006_clasificar_publico_clases_existentes'),
        ('cortesias', '0003_clasecortesia_contactado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasecortesia',
            name='fecha_clase',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la clase solicitada'),
        ),
        migrations.AlterField(
            model_name='clasecortesia',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cortesias', to='clases.claseprogramada'),
        ),
    ]
