# Generated by Django 5.2.13 on 2026-08-06 00:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alumno_foto_perfil'),
        ('cortesias', '0004_fecha_clase_y_seleccion_pendiente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSeguimientoCortesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(default='Queremos verte nuevamente en Galeras BJJ', max_length=180)),
                ('mensaje', models.TextField(default='Gracias por acompañarnos en tu clase de cortesía. Nos gustaría invitarte a continuar entrenando con nosotros.')),
                ('publicidad', models.ImageField(blank=True, null=True, upload_to='cortesias/publicidad/')),
                ('dias_espera', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(365)], verbose_name='Días después de la clase para el primer correo')),
                ('intervalo_dias', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Intervalo mínimo entre correos')),
                ('maximo_envios', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Máximo de correos por persona')),
                ('activo', models.BooleanField(default=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seguimiento de cortesías por correo',
                'verbose_name_plural': 'Seguimiento de cortesías por correo',
            },
        ),
        migrations.AddField(
            model_name='clasecortesia',
            name='alumno_convertido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cortesias_origen', to='alumnos.alumno'),
        ),
        migrations.AddField(
            model_name='clasecortesia',
            name='asistencia_confirmada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cortesias_asistencia_confirmada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clasecortesia',
            name='asistio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clasecortesia',
            name='cantidad_correos_seguimiento',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clasecortesia',
            name='contactado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cortesias_contactadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clasecortesia',
            name='fecha_confirmacion_asistencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clasecortesia',
            name='fecha_conversion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clasecortesia',
            name='fecha_ultimo_correo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
