# Generated by Django 5.2.13 on 2026-05-04 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECORDATORIO_PAGO', 'Recordatorio de pago'), ('VENCIMIENTO', 'Vencimiento'), ('MORA', 'Mora'), ('PAGO_APROBADO', 'Pago aprobado'), ('PAGO_RECHAZADO', 'Pago rechazado')], max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('FALLIDA', 'Fallida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('canal', models.CharField(choices=[('INTERNA', 'Interna'), ('EMAIL', 'Correo electrónico')], default='INTERNA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_programada'],
            },
        ),
    ]
