# Generated by Django 5.2.13 on 2026-10-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('RECORDATORIO_PAGO', 'Recordatorio de pago'), ('VENCIMIENTO', 'Vencimiento'), ('MORA', 'Mora'), ('PAGO_APROBADO', 'Pago aprobado'), ('PAGO_RECHAZADO', 'Pago rechazado'), ('RECOMPENSA', 'Recompensa recibida')], max_length=30),
        ),
    ]
