# Generated by Django 5.2.13 on 2026-05-10 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopagoqr',
            name='cuenta_financiera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metodos_pago', to='finanzas.cuentafinanciera'),
        ),
    ]
