# Generated by Django 5.2.13 on 2026-06-08 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_metodopagoqr_cuenta_financiera'),
        ('planes', '0005_remove_plan_clases_semanales_plan_clases_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='planes.plan'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='suscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='planes.suscripcion'),
        ),
    ]
