# Generated by Django 5.2.13 on 2026-07-19 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


def preparar_pagos_existentes(apps, schema_editor):
    Pago = apps.get_model('pagos', 'Pago')
    Categoria = apps.get_model('finanzas', 'CategoriaFinanciera')
    for pago in Pago.objects.select_related('alumno__user').all().iterator():
        pago.token_comprobante = uuid.uuid4()
        if pago.alumno_id:
            nombre_alumno = (
                f'{pago.alumno.user.first_name} {pago.alumno.user.last_name}'.strip()
                or pago.alumno.user.username
            )
            pago.pagador_nombre = pago.alumno.nombre_acudiente or nombre_alumno
            pago.pagador_documento = pago.alumno.documento_acudiente or pago.alumno.documento
            pago.pagador_correo = pago.alumno.user.email or ''
        pago.save(update_fields=[
            'token_comprobante', 'pagador_nombre', 'pagador_documento',
            'pagador_correo',
        ])
    for nombre in ('Promociones academia', 'Eventos academia', 'Otros ingresos academia'):
        Categoria.objects.get_or_create(
            nombre=nombre, defaults={'tipo': 'INGRESO', 'activa': True}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alumno_documento_acudiente_and_more'),
        ('pagos', '0003_pago_plan_alter_pago_suscripcion'),
        ('planes', '0009_suscripcion_detalle_beneficio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SEMINARIO', 'Seminario'), ('TORNEO', 'Torneo'), ('CAMPAMENTO', 'Campamento'), ('OTRO', 'Otro evento')], max_length=20)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite_inscripcion', models.DateTimeField(blank=True, null=True)),
                ('lugar', models.CharField(max_length=200)),
                ('precio_estudiante', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_externo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cupo_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('publico', models.CharField(choices=[('TODOS', 'Todo público'), ('ADULTOS', 'Adultos'), ('MENORES', 'Menores de edad'), ('ESTUDIANTES', 'Solo estudiantes')], default='TODOS', max_length=20)),
                ('requisitos', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('publicada_home', models.BooleanField(default=False)),
                ('destacada', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='comprobante_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pago',
            name='concepto_detalle',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='pago',
            name='correo_comprobante_enviado_a',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='pago',
            name='duplicado_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posibles_duplicados', to='pagos.pago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='error_envio_comprobante',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_comprobante',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_envio_comprobante',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='justificacion_duplicado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='numero_comprobante',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='pagador_correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='pago',
            name='pagador_documento',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pago',
            name='pagador_nombre',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='pago',
            name='posible_duplicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('MENSUALIDAD', 'Mensualidad'), ('PROMOCION', 'Mensualidad con promoción'), ('EVENTO', 'Seminario, torneo o evento'), ('OTRO', 'Otro ingreso de academia')], default='MENSUALIDAD', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='token_comprobante',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='pago',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='alumnos.alumno'),
        ),
        migrations.RunPython(preparar_pagos_existentes, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.TextField()),
                ('tipo_beneficio', models.CharField(choices=[('PORCENTAJE', 'Descuento porcentual'), ('PRECIO_FIJO', 'Precio fijo'), ('DIAS_EXTRA', 'Días adicionales')], max_length=20)),
                ('valor_beneficio', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje, precio fijo o número de días, según el beneficio.', max_digits=12)),
                ('condiciones', models.TextField(blank=True)),
                ('publico', models.CharField(choices=[('TODOS', 'Todos los estudiantes'), ('NUEVOS', 'Estudiantes nuevos'), ('ACTIVOS', 'Estudiantes activos')], default='TODOS', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('maximo_usos', models.PositiveIntegerField(blank=True, null=True)),
                ('un_uso_por_alumno', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='promociones/')),
                ('publicada_home', models.BooleanField(default=False)),
                ('destacada', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=10)),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promociones', to='planes.plan')),
            ],
            options={
                'ordering': ['orden', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AplicacionPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APLICADA', 'Aplicada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_promocion', to='alumnos.alumno')),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacion_promocion', to='pagos.pago')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='pagos.promocion')),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pagos.promocion'),
        ),
        migrations.CreateModel(
            name='InscripcionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participante_nombre', models.CharField(max_length=180)),
                ('participante_documento', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('acudiente_nombre', models.CharField(blank=True, max_length=180)),
                ('acudiente_documento', models.CharField(blank=True, max_length=30)),
                ('acudiente_telefono', models.CharField(blank=True, max_length=30)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('acepta_consentimiento', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de pago o revisión'), ('CONFIRMADA', 'Confirmada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada'), ('LISTA_ESPERA', 'Lista de espera')], default='PENDIENTE', max_length=20)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones_eventos', to='alumnos.alumno')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='pagos.evento')),
                ('pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscripcion_evento', to='pagos.pago')),
            ],
            options={
                'ordering': ['-creada'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'CANCELADA'), _negated=True), fields=('evento', 'participante_documento'), name='inscripcion_evento_documento_activa_unica')],
            },
        ),
        migrations.AlterField(
            model_name='pago',
            name='token_comprobante',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
