# Generated by Django 5.2.13 on 2026-07-19 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_comprobantes_pagos_aprobados_existentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('genero', models.CharField(choices=[('MIXTA', 'Mixta'), ('FEMENINA', 'Femenina'), ('MASCULINA', 'Masculina')], default='MIXTA', max_length=15)),
                ('edad_minima', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('edad_maxima', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('peso_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('peso_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nivel', models.CharField(blank=True, help_text='Ejemplo: principiante, cinturón blanco o avanzado.', max_length=100)),
                ('cupo_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=10)),
                ('activa', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='pagos.evento')),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='inscripcionevento',
            name='categoria_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='pagos.categoriaevento'),
        ),
        migrations.AddConstraint(
            model_name='categoriaevento',
            constraint=models.UniqueConstraint(fields=('evento', 'nombre'), name='categoria_nombre_unico_por_evento'),
        ),
    ]
