# Generated by Django 5.2.13 on 2026-07-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_categoriaevento_inscripcionevento_categoria_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='alcance_torneo',
            field=models.CharField(choices=[('INTERNO', 'Interno: solo estudiantes de la academia'), ('ABIERTO', 'Abierto: participantes de otras academias')], default='INTERNO', help_text='Solo se aplica cuando el evento es un torneo.', max_length=15),
        ),
        migrations.AddField(
            model_name='evento',
            name='consentimiento_evento',
            field=models.TextField(blank=True, help_text='Texto que deberá aceptar y firmar cada participante. Puede ser diferente para cada evento.'),
        ),
        migrations.AddField(
            model_name='inscripcionevento',
            name='academia_origen',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='inscripcionevento',
            name='fecha_firma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcionevento',
            name='firma_base64',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inscripcionevento',
            name='foto_participante',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/participantes/'),
        ),
        migrations.AddField(
            model_name='inscripcionevento',
            name='ip_firma',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcionevento',
            name='texto_consentimiento',
            field=models.TextField(blank=True),
        ),
    ]
