# Generated by Django 5.2.13 on 2026-07-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_evento_alcance_torneo_evento_consentimiento_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='reglamento_adultos',
            field=models.TextField(blank=True, help_text='Reglamento que aceptarán los participantes mayores de edad.'),
        ),
        migrations.AddField(
            model_name='evento',
            name='reglamento_menores',
            field=models.TextField(blank=True, help_text='Reglamento aplicable a menores y que deberá aceptar su acudiente.'),
        ),
        migrations.AddField(
            model_name='inscripcionevento',
            name='acepta_reglamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcionevento',
            name='texto_reglamento',
            field=models.TextField(blank=True),
        ),
    ]
