# Generated by Django 5.2.13 on 2026-07-19 16:28

import config.file_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_evento_reglamento_adultos_evento_reglamento_menores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='video',
            field=models.FileField(blank=True, help_text='Video corto MP4 o WEBM, máximo 25 MB.', null=True, upload_to='eventos/videos/', validators=[config.file_validation.validate_short_video]),
        ),
        migrations.AddField(
            model_name='promocion',
            name='video',
            field=models.FileField(blank=True, help_text='Video corto MP4 o WEBM, máximo 25 MB.', null=True, upload_to='promociones/videos/', validators=[config.file_validation.validate_short_video]),
        ),
    ]
