# Generated by Django 5.2.13 on 2026-07-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0009_evento_video_promocion_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_inicio_inscripcion',
            field=models.DateTimeField(blank=True, help_text='Si se deja vacío, las inscripciones quedan abiertas inmediatamente.', null=True, verbose_name='Inicio de inscripciones'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_limite_inscripcion',
            field=models.DateTimeField(blank=True, help_text='Es independiente de las fechas de inicio y finalización del evento.', null=True, verbose_name='Cierre de inscripciones'),
        ),
    ]
