# Generated by Django 5.2.13 on 2026-07-19 18:16

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


def enlazar_academias_existentes(apps, schema_editor):
    Academia = apps.get_model('pagos', 'AcademiaCompetidora')
    Inscripcion = apps.get_model('pagos', 'InscripcionEvento')
    for inscripcion in Inscripcion.objects.all().iterator():
        nombre = (inscripcion.academia_origen or '').strip()
        if not nombre and inscripcion.alumno_id:
            nombre = 'Galeras BJJ'
        if not nombre:
            continue
        academia = Academia.objects.filter(nombre__iexact=nombre).first()
        if not academia:
            academia = Academia.objects.create(nombre=nombre)
        inscripcion.academia_equipo_id = academia.id
        inscripcion.save(update_fields=['academia_equipo'])


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alumno_documento_acudiente_and_more'),
        ('pagos', '0010_evento_fecha_inicio_inscripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademiaCompetidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='academias/logos/')),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='inscripcionevento',
            name='inscripcion_evento_documento_activa_unica',
        ),
        migrations.AddField(
            model_name='categoriaevento',
            name='tipo_categoria',
            field=models.CharField(choices=[('REGULAR', 'Categoría regular'), ('SUPERIOR', 'Categoría superior'), ('ABSOLUTA', 'Categoría absoluta')], default='REGULAR', help_text='Solo una categoría superior o absoluta puede utilizarse como segunda inscripción del mismo participante.', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='academiacompetidora',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='academia_competidora_nombre_unico'),
        ),
        migrations.AddField(
            model_name='inscripcionevento',
            name='academia_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='pagos.academiacompetidora'),
        ),
        migrations.RunPython(
            enlazar_academias_existentes,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='inscripcionevento',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('estado', 'CANCELADA'), _negated=True), ('categoria_evento__isnull', False)), fields=('evento', 'participante_documento', 'categoria_evento'), name='inscripcion_categoria_documento_activa_unica'),
        ),
        migrations.AddConstraint(
            model_name='inscripcionevento',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('estado', 'CANCELADA'), _negated=True), ('categoria_evento__isnull', True)), fields=('evento', 'participante_documento'), name='inscripcion_sin_categoria_documento_activa_unica'),
        ),
    ]
