# Generated by Django 5.2.13 on 2026-07-19 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0011_academiacompetidora_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LlaveCategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('actualizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llaves_evento_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llave_publicada', to='pagos.categoriaevento')),
            ],
            options={
                'verbose_name': 'Llave de categoría',
                'verbose_name_plural': 'Llaves de categorías',
            },
        ),
    ]
