# Generated by Django 5.2.13 on 2026-08-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0013_unificar_academia_galeras'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: Jornada adultos o Jornada infantil.', max_length=120)),
                ('publico', models.CharField(choices=[('TODOS', 'Todo público'), ('ADULTOS', 'Adultos'), ('MENORES', 'Infantil / menores de edad')], default='TODOS', max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('precio_estudiante', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_externo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cupo_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='pagos.evento')),
            ],
            options={'ordering': ['orden', 'fecha_inicio', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='inscripcionevento',
            name='inscripcion_sin_categoria_documento_activa_unica',
        ),
        migrations.AddField(
            model_name='inscripcionevento',
            name='jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='pagos.jornadaevento'),
        ),
        migrations.AddField(
            model_name='inscripcionevento',
            name='tarifa_publicada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='inscripcionevento',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('estado', 'CANCELADA'), _negated=True), ('categoria_evento__isnull', True), ('jornada__isnull', True)), fields=('evento', 'participante_documento'), name='inscripcion_sin_categoria_documento_activa_unica'),
        ),
        migrations.AddConstraint(
            model_name='inscripcionevento',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('estado', 'CANCELADA'), _negated=True), ('categoria_evento__isnull', True), ('jornada__isnull', False)), fields=('evento', 'participante_documento', 'jornada'), name='inscripcion_jornada_documento_activa_unica'),
        ),
    ]
