# Generated by Django 5.2.13 on 2026-07-19 01:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClienteTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('NIT', 'NIT'), ('PAS', 'Pasaporte'), ('TI', 'Tarjeta de identidad'), ('OTRO', 'Otro')], max_length=10)),
                ('numero_documento', models.CharField(max_length=30, unique=True)),
                ('telefono_whatsapp', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('acepta_whatsapp', models.BooleanField(default=False, help_text='El cliente autorizó recibir comprobantes y recordatorios por WhatsApp.')),
                ('preferencial', models.BooleanField(default=False)),
                ('descuento_preferencial', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente de tienda',
                'verbose_name_plural': 'Clientes de tienda',
                'ordering': ['nombres'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=220)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'verbose_name': 'Detalle de venta de tienda',
                'verbose_name_plural': 'Detalles de venta de tienda',
            },
        ),
        migrations.CreateModel(
            name='SubcategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subcategoría de producto',
                'verbose_name_plural': 'Subcategorías de producto',
                'ordering': ['categoria__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='VentaTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=24, unique=True)),
                ('modalidad', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], max_length=10)),
                ('estado', models.CharField(choices=[('PAGADA', 'Pagada'), ('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago parcial'), ('ANULADA', 'Anulada')], max_length=12)),
                ('moneda', models.CharField(choices=[('COP', 'Pesos colombianos (COP)'), ('USD', 'Dólares (USD)')], max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Venta de tienda',
                'verbose_name_plural': 'Ventas de tienda',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='cuentatienda',
            options={'ordering': ['moneda', '-activa', 'nombre'], 'verbose_name': 'Cuenta de tienda', 'verbose_name_plural': 'Cuentas de tienda'},
        ),
        migrations.AlterModelOptions(
            name='productotienda',
            options={'ordering': ['-activo', 'nombre', 'color', 'talla'], 'verbose_name': 'Producto de tienda', 'verbose_name_plural': 'Productos de tienda'},
        ),
        migrations.AddField(
            model_name='ajusteinventario',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='cuentatienda',
            name='fecha_inactivacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentatienda',
            name='fecha_saldo_inicial',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='cuentatienda',
            name='moneda',
            field=models.CharField(choices=[('COP', 'Pesos colombianos (COP)'), ('USD', 'Dólares (USD)')], default='COP', max_length=3),
        ),
        migrations.AddField(
            model_name='movimientotienda',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='movimientotienda',
            name='moneda',
            field=models.CharField(choices=[('COP', 'Pesos colombianos (COP)'), ('USD', 'Dólares (USD)')], default='COP', max_length=3),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='codigo_producto',
            field=models.CharField(blank=True, help_text='Código maestro que agrupa todas las variantes del mismo producto.', max_length=60),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='codigo_proveedor',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='disciplina',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='fecha_inactivacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='genero',
            field=models.CharField(blank=True, choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('UNISEX', 'Unisex')], max_length=10),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='linea_modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='material',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='moneda',
            field=models.CharField(choices=[('COP', 'Pesos colombianos (COP)'), ('USD', 'Dólares (USD)')], default='COP', max_length=3),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='motivo_inactivacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='proveedor',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='publico',
            field=models.CharField(blank=True, choices=[('ADULTO', 'Adulto'), ('NINO', 'Niño'), ('TODOS', 'Todos')], max_length=10),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='talla',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='unidad',
            field=models.CharField(default='Unidad', max_length=30),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='url_imagen',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='cuentatienda',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cuentatienda',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='movimientotienda',
            name='origen',
            field=models.CharField(choices=[('VENTA', 'Venta de contado'), ('ABONO', 'Abono de venta a crédito'), ('COMPRA', 'Compra de producto'), ('GASTO', 'Gasto general')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movimientotienda',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='productotienda',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productotienda',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productotienda',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productotienda',
            name='referencia',
            field=models.CharField(blank=True, help_text='SKU único de esta variante.', max_length=60, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='cuentatienda',
            constraint=models.UniqueConstraint(fields=('nombre', 'moneda'), name='cuenta_tienda_nombre_moneda_unicos'),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='tienda.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='detalleventatienda',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='tienda.productotienda'),
        ),
        migrations.AddField(
            model_name='subcategoriaproducto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='tienda.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='tienda.subcategoriaproducto'),
        ),
        migrations.AddField(
            model_name='ventatienda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='tienda.clientetienda'),
        ),
        migrations.AddField(
            model_name='ventatienda',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_tienda_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleventatienda',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.ventatienda'),
        ),
        migrations.AddField(
            model_name='movimientotienda',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='tienda.ventatienda'),
        ),
        migrations.AddConstraint(
            model_name='subcategoriaproducto',
            constraint=models.UniqueConstraint(fields=('categoria', 'nombre'), name='subcategoria_unica_por_categoria'),
        ),
    ]
