# Generated by Django 5.2.13 on 2026-07-19 01:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_importar_catalogo_gis_bross'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventatienda',
            name='numero_cuotas',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='CuotaVentaTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago parcial'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=10)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='tienda.ventatienda')),
            ],
            options={
                'verbose_name': 'Cuota de venta',
                'verbose_name_plural': 'Cuotas de venta',
                'ordering': ['fecha_vencimiento', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='AplicacionAbonoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones_cuotas', to='tienda.movimientotienda')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='tienda.cuotaventatienda')),
            ],
            options={
                'verbose_name': 'Aplicación de abono a cuota',
                'verbose_name_plural': 'Aplicaciones de abonos a cuotas',
            },
        ),
        migrations.AddConstraint(
            model_name='cuotaventatienda',
            constraint=models.UniqueConstraint(fields=('venta', 'numero'), name='numero_cuota_unico_por_venta'),
        ),
    ]
