# Generated by Django 5.2.13 on 2026-07-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_crear_cuotas_creditos_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventatienda',
            name='email_enviado_a',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ventatienda',
            name='error_envio_correo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ventatienda',
            name='fecha_envio_correo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
