# Generated by Django 5.2.13 on 2026-07-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_ventatienda_email_enviado_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productotienda',
            name='codigo_producto',
            field=models.CharField(blank=True, help_text='(Código maestro)', max_length=60),
        ),
    ]
