# Generated by Django 5.2.13 on 2026-08-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_productotienda_codigo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventatienda',
            name='referencia_externa',
            field=models.CharField(blank=True, help_text='Factura, comprobante o referencia del sistema anterior.', max_length=80),
        ),
        migrations.AddField(
            model_name='ventatienda',
            name='tipo_registro',
            field=models.CharField(choices=[('VENTA', 'Venta de tienda'), ('CARTERA_INICIAL', 'Cartera anterior')], default='VENTA', max_length=20),
        ),
    ]
