# Generated by Django 5.2.13 on 2026-08-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_ventatienda_referencia_externa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientotienda',
            name='transferencia_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Identificador compartido por la salida y la entrada de una transferencia.', null=True),
        ),
        migrations.AlterField(
            model_name='movimientotienda',
            name='origen',
            field=models.CharField(choices=[('VENTA', 'Venta de contado'), ('ABONO', 'Abono de venta a crédito'), ('COMPRA', 'Compra de producto'), ('GASTO', 'Gasto general'), ('TRANSFERENCIA', 'Transferencia entre cuentas')], max_length=20),
        ),
    ]
