# Generated by Django 5.2.13 on 2026-08-19 02:06

import django.db.models.deletion
from django.db import migrations, models


def crear_categorias_iniciales(apps, schema_editor):
    Categoria = apps.get_model('tienda', 'CategoriaMovimientoTienda')
    categorias = (
        ('OTROS INGRESOS OPERACIONALES', 'INGRESO', 'OPERACIONAL'),
        ('DONACIONES Y APORTES', 'INGRESO', 'NO_OPERACIONAL'),
        ('OTROS INGRESOS NO OPERACIONALES', 'INGRESO', 'NO_OPERACIONAL'),
        ('ENVÍOS Y DESPACHOS', 'EGRESO', 'OPERACIONAL'),
        ('VIÁTICOS', 'EGRESO', 'OPERACIONAL'),
        ('OTROS GASTOS OPERACIONALES', 'EGRESO', 'OPERACIONAL'),
        ('OTROS GASTOS NO OPERACIONALES', 'EGRESO', 'NO_OPERACIONAL'),
    )
    for nombre, tipo, naturaleza in categorias:
        Categoria.objects.get_or_create(
            nombre=nombre,
            tipo=tipo,
            naturaleza=naturaleza,
            defaults={'activa': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_transferencias_entre_cuentas'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientotienda',
            name='soporte',
            field=models.FileField(blank=True, help_text='Factura, recibo, comprobante, imagen o PDF relacionado.', null=True, upload_to='tienda/soportes/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='movimientotienda',
            name='origen',
            field=models.CharField(choices=[('VENTA', 'Venta de contado'), ('ABONO', 'Abono de venta a crédito'), ('COMPRA', 'Compra de producto'), ('GASTO', 'Gasto general'), ('TRANSFERENCIA', 'Transferencia entre cuentas'), ('OTRO_INGRESO', 'Otro ingreso')], max_length=20),
        ),
        migrations.CreateModel(
            name='CategoriaMovimientoTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Gasto')], max_length=10)),
                ('naturaleza', models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('NO_OPERACIONAL', 'No operacional')], default='OPERACIONAL', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría contable de tienda',
                'verbose_name_plural': 'Categorías contables de tienda',
                'ordering': ['tipo', 'naturaleza', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'tipo', 'naturaleza'), name='categoria_mov_tienda_unica')],
            },
        ),
        migrations.AddField(
            model_name='movimientotienda',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='tienda.categoriamovimientotienda'),
        ),
        migrations.RunPython(
            crear_categorias_iniciales,
            migrations.RunPython.noop,
        ),
    ]
