# Generated by Django 5.2.13 on 2026-08-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_categorias_contables_independientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productotienda',
            name='referencia',
            field=models.CharField(blank=True, help_text='SKU o referencia comercial. Puede repetirse en varios productos o variantes.', max_length=60, null=True),
        ),
    ]
