# Generated by Django 5.2.13 on 2026-08-21 00:20

import django.db.models.deletion
from django.db import migrations, models


def migrar_catalogos_existentes(apps, schema_editor):
    Producto = apps.get_model('tienda', 'ProductoTienda')
    Marca = apps.get_model('tienda', 'MarcaProducto')
    Linea = apps.get_model('tienda', 'LineaModeloProducto')
    Disciplina = apps.get_model('tienda', 'DisciplinaProducto')

    for producto in Producto.objects.all().iterator():
        nombre_marca = (producto.marca_texto or '').strip()
        nombre_linea = (producto.linea_modelo_texto or '').strip()
        nombre_disciplina = (producto.disciplina_texto or '').strip()

        marca = None
        if nombre_marca or nombre_linea:
            nombre_marca = nombre_marca or 'SIN MARCA'
            marca = Marca.objects.filter(nombre__iexact=nombre_marca).first()
            if not marca:
                marca = Marca.objects.create(nombre=nombre_marca)
            producto.marca_id = marca.id

        if nombre_linea and marca:
            linea = Linea.objects.filter(
                marca_id=marca.id,
                nombre__iexact=nombre_linea,
            ).first()
            if not linea:
                linea = Linea.objects.create(marca_id=marca.id, nombre=nombre_linea)
            producto.linea_modelo_id = linea.id

        if nombre_disciplina:
            disciplina = Disciplina.objects.filter(
                nombre__iexact=nombre_disciplina
            ).first()
            if not disciplina:
                disciplina = Disciplina.objects.create(nombre=nombre_disciplina)
            producto.disciplina_id = disciplina.id

        producto.save(update_fields=['marca', 'linea_modelo', 'disciplina'])


def restaurar_textos(apps, schema_editor):
    Producto = apps.get_model('tienda', 'ProductoTienda')
    for producto in Producto.objects.select_related(
        'marca', 'linea_modelo', 'disciplina'
    ).all().iterator():
        producto.marca_texto = producto.marca.nombre if producto.marca_id else ''
        producto.linea_modelo_texto = (
            producto.linea_modelo.nombre if producto.linea_modelo_id else ''
        )
        producto.disciplina_texto = (
            producto.disciplina.nombre if producto.disciplina_id else ''
        )
        producto.save(update_fields=[
            'marca_texto', 'linea_modelo_texto', 'disciplina_texto'
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_permitir_sku_repetido'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Disciplina de producto',
                'verbose_name_plural': 'Disciplinas de productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LineaModeloProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Línea o modelo de producto',
                'verbose_name_plural': 'Líneas y modelos de productos',
                'ordering': ['marca__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MarcaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca de producto',
                'verbose_name_plural': 'Marcas de productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.RenameField(
            model_name='productotienda',
            old_name='disciplina',
            new_name='disciplina_texto',
        ),
        migrations.AddField(
            model_name='productotienda',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='tienda.disciplinaproducto'),
        ),
        migrations.RenameField(
            model_name='productotienda',
            old_name='linea_modelo',
            new_name='linea_modelo_texto',
        ),
        migrations.AddField(
            model_name='productotienda',
            name='linea_modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='tienda.lineamodeloproducto'),
        ),
        migrations.AddField(
            model_name='lineamodeloproducto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_modelos', to='tienda.marcaproducto'),
        ),
        migrations.RenameField(
            model_name='productotienda',
            old_name='marca',
            new_name='marca_texto',
        ),
        migrations.AddField(
            model_name='productotienda',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='tienda.marcaproducto'),
        ),
        migrations.RunPython(migrar_catalogos_existentes, restaurar_textos),
        migrations.RemoveField(
            model_name='productotienda',
            name='marca_texto',
        ),
        migrations.RemoveField(
            model_name='productotienda',
            name='linea_modelo_texto',
        ),
        migrations.RemoveField(
            model_name='productotienda',
            name='disciplina_texto',
        ),
        migrations.AddConstraint(
            model_name='lineamodeloproducto',
            constraint=models.UniqueConstraint(fields=('marca', 'nombre'), name='linea_modelo_unica_por_marca'),
        ),
    ]
