# Generated by Django 5.2.13 on 2026-09-28 22:15

import django.db.models.deletion
from django.db import migrations, models


def crear_catalogo_proveedores(apps, schema_editor):
    Producto = apps.get_model('tienda', 'ProductoTienda')
    Proveedor = apps.get_model('tienda', 'ProveedorTienda')
    for producto in Producto.objects.exclude(
        proveedor='', codigo_proveedor=''
    ).iterator():
        nombre = (producto.proveedor or '').strip()
        codigo = (producto.codigo_proveedor or '').strip().upper()
        proveedor = None
        if codigo:
            proveedor = Proveedor.objects.filter(codigo__iexact=codigo).first()
        if proveedor is None and nombre:
            proveedor = Proveedor.objects.filter(nombre__iexact=nombre).first()
        if proveedor is None:
            codigo_nuevo = codigo or f'LEGACY-{producto.pk}'
            nombre_nuevo = nombre or f'Proveedor {codigo_nuevo}'
            sufijo = 2
            base_codigo = codigo_nuevo
            while Proveedor.objects.filter(codigo__iexact=codigo_nuevo).exists():
                codigo_nuevo = f'{base_codigo}-{sufijo}'
                sufijo += 1
            sufijo = 2
            base_nombre = nombre_nuevo
            while Proveedor.objects.filter(nombre__iexact=nombre_nuevo).exists():
                nombre_nuevo = f'{base_nombre} ({sufijo})'
                sufijo += 1
            proveedor = Proveedor.objects.create(
                codigo=codigo_nuevo,
                nombre=nombre_nuevo,
            )
        elif codigo and proveedor.codigo.startswith('LEGACY-'):
            if not Proveedor.objects.filter(codigo__iexact=codigo).exclude(
                pk=proveedor.pk
            ).exists():
                proveedor.codigo = codigo
                proveedor.save(update_fields=['codigo'])
        producto.proveedor_catalogo_id = proveedor.pk
        producto.save(update_fields=['proveedor_catalogo'])


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_catalogos_marca_linea_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor de tienda',
                'verbose_name_plural': 'Proveedores de tienda',
                'ordering': ['-activo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='productotienda',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tienda/productos/', verbose_name='Foto del producto'),
        ),
        migrations.AddField(
            model_name='productotienda',
            name='proveedor_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='tienda.proveedortienda', verbose_name='Proveedor'),
        ),
        migrations.RunPython(
            crear_catalogo_proveedores,
            migrations.RunPython.noop,
        ),
    ]
