# Generated by Django 5.2.13 on 2026-09-28 22:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_proveedores_y_fotos_productos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ventatienda',
            name='entregada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ventatienda',
            name='fecha_entrega_estimada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatienda',
            name='fecha_entrega_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatienda',
            name='tipo_entrega',
            field=models.CharField(choices=[('INMEDIATA', 'Entrega inmediata'), ('SOBRE_PEDIDO', 'Sobre pedido')], default='INMEDIATA', max_length=20),
        ),
        migrations.CreateModel(
            name='CompraProveedorTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=24, unique=True)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(choices=[('COP', 'Pesos colombianos (COP)'), ('USD', 'Dólares (USD)')], max_length=3)),
                ('modalidad', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], max_length=10)),
                ('estado', models.CharField(choices=[('PAGADA', 'Pagada'), ('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago parcial')], max_length=12)),
                ('abono_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('numero_cuotas', models.PositiveSmallIntegerField(default=1)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_proveedor', to='tienda.productotienda')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='tienda.proveedortienda')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_tienda_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra a proveedor',
                'verbose_name_plural': 'Compras a proveedores',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='movimientotienda',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='tienda.compraproveedortienda'),
        ),
        migrations.CreateModel(
            name='CuotaCompraTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago parcial'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='tienda.compraproveedortienda')),
            ],
            options={
                'ordering': ['fecha_vencimiento', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('compra', 'numero'), name='numero_cuota_unico_por_compra')],
            },
        ),
    ]
