# Generated by Django 5.2.13 on 2026-09-28 23:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_ventatienda_entregada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productotienda',
            name='disponible_sobre_pedido',
            field=models.BooleanField(default=False, help_text='Permite ofrecerlo en el catálogo aunque no tenga existencias.'),
        ),
        migrations.CreateModel(
            name='PedidoTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=24, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('NIT', 'NIT'), ('PAS', 'Pasaporte'), ('TI', 'Tarjeta de identidad'), ('OTRO', 'Otro')], max_length=10)),
                ('numero_documento', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=220)),
                ('modalidad_entrega', models.CharField(choices=[('ACADEMIA', 'Recoger en la academia'), ('DOMICILIO', 'Entrega a domicilio'), ('ENVIO', 'Envío a otra ciudad')], max_length=12)),
                ('moneda', models.CharField(choices=[('COP', 'Pesos colombianos (COP)'), ('USD', 'Dólares (USD)')], max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('referencia_pago', models.CharField(max_length=100)),
                ('soporte_pago', models.FileField(upload_to='tienda/pedidos/%Y/%m/')),
                ('estado', models.CharField(choices=[('PAGO_REVISION', 'Pago en revisión'), ('APROBADO', 'Aprobado'), ('PREPARANDO', 'Preparando'), ('LISTO', 'Listo para entregar'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('RECHAZADO', 'Pago rechazado'), ('CANCELADO', 'Cancelado')], default='PAGO_REVISION', max_length=20)),
                ('observaciones_cliente', models.TextField(blank=True)),
                ('observaciones_administrativas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cuenta_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_publicos', to='tienda.cuentatienda')),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_publico', to='tienda.ventatienda')),
            ],
            options={
                'verbose_name': 'Pedido público de tienda',
                'verbose_name_plural': 'Pedidos públicos de tienda',
                'ordering': ['-creado', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=220)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sobre_pedido', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido_publico', to='tienda.productotienda')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.pedidotienda')),
            ],
        ),
    ]
