# Generated by Django 5.2.13 on 2026-05-04 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('disciplina', models.CharField(choices=[('JIU_JITSU', 'Jiu Jitsu'), ('MUAY_THAI', 'Muay Thai'), ('MMA', 'MMA'), ('OTRA', 'Otra')], max_length=30)),
                ('cupo_maximo', models.PositiveIntegerField(default=20)),
                ('activa', models.BooleanField(default=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='instructores.instructor')),
            ],
            options={
                'verbose_name': 'Clase programada',
                'verbose_name_plural': 'Clases programadas',
                'ordering': ['dia', 'hora_inicio'],
            },
        ),
    ]
