# Generated by Django 5.2.13 on 2026-05-04 23:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_disciplina'),
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_clase', models.DateField()),
                ('fecha_confirmacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('FUERA_DE_TIEMPO', 'Fuera de tiempo'), ('CANCELADA', 'Cancelada')], default='CONFIRMADA', max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='alumnos.alumno')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='clases.claseprogramada')),
            ],
            options={
                'verbose_name': 'Asistencia a clase',
                'verbose_name_plural': 'Asistencias a clases',
                'ordering': ['-fecha_clase', '-fecha_confirmacion'],
                'unique_together': {('alumno', 'clase', 'fecha_clase')},
            },
        ),
    ]
