# Generated by Django 5.2.13 on 2026-06-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_asistenciaclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseprogramada',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
