# Generated by Django 5.2.13 on 2026-06-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_claseprogramada_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claseprogramada',
            name='disciplina',
            field=models.CharField(choices=[('JIU_JITSU', 'Jiu Jitsu'), ('MUAY_THAI', 'Muay Thai'), ('MMA', 'MMA'), ('MMA-MUAYTHAI', 'MMA & Muay Thai'), ('OTRA', 'Otra')], max_length=30),
        ),
    ]
