# Generated by Django 5.2.13 on 2026-07-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_alter_claseprogramada_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseprogramada',
            name='publico_objetivo',
            field=models.CharField(choices=[('TODOS', 'Adultos y menores'), ('ADULTO', 'Adultos'), ('MENOR', 'Menores de edad')], default='TODOS', max_length=10, verbose_name='Público objetivo'),
        ),
    ]
