# Generated by Django 5.2.13 on 2026-08-13 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_alumno_permitir_asistencia_vencida'),
        ('clases', '0006_clasificar_publico_clases_existentes'),
        ('instructores', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistenciaclase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asistenciaclase',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='instructores.instructor'),
        ),
        migrations.AlterField(
            model_name='asistenciaclase',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='alumnos.alumno'),
        ),
        migrations.AddConstraint(
            model_name='asistenciaclase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('alumno__isnull', False), ('instructor__isnull', True)), models.Q(('alumno__isnull', True), ('instructor__isnull', False)), _connector='OR'), name='asistencia_tiene_un_solo_perfil'),
        ),
        migrations.AddConstraint(
            model_name='asistenciaclase',
            constraint=models.UniqueConstraint(condition=models.Q(('alumno__isnull', False)), fields=('alumno', 'clase', 'fecha_clase'), name='asistencia_alumno_clase_fecha_unica'),
        ),
        migrations.AddConstraint(
            model_name='asistenciaclase',
            constraint=models.UniqueConstraint(condition=models.Q(('instructor__isnull', False)), fields=('instructor', 'clase', 'fecha_clase'), name='asistencia_instructor_clase_fecha_unica'),
        ),
    ]
