# Generated by Django 5.2.13 on 2026-04-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='suscripcion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVA')), fields=('alumno',), name='unique_suscripcion_activa_por_alumno'),
        ),
    ]
