# Generated by Django 5.2.13 on 2026-05-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_asistenciaclase'),
        ('planes', '0002_suscripcion_unique_suscripcion_activa_por_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='tipo_acceso',
            field=models.CharField(choices=[('CLASES_ESPECIFICAS', 'Clases específicas'), ('TODAS_LAS_CLASES', 'Todas las clases')], default='CLASES_ESPECIFICAS', max_length=30),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='clases_asignadas',
            field=models.ManyToManyField(blank=True, related_name='suscripciones', to='clases.claseprogramada'),
        ),
    ]
