# Generated by Django 5.2.13 on 2026-06-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_plan_tipo_acceso_suscripcion_clases_asignadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='tipo_acceso',
        ),
        migrations.AddField(
            model_name='plan',
            name='clases_semanales',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='plan',
            name='disciplina',
            field=models.CharField(choices=[('JIUJITSU', 'Jiujitsu'), ('MUAY_THAI', 'Muay Thai'), ('MIXTO', 'Mixto')], default='JIUJITSU', max_length=20),
        ),
    ]
