# Generated by Django 5.2.13 on 2026-06-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0004_remove_plan_tipo_acceso_plan_clases_semanales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='clases_semanales',
        ),
        migrations.AddField(
            model_name='plan',
            name='clases_mes',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
