# Generated by Django 5.2.13 on 2026-06-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0005_remove_plan_clases_semanales_plan_clases_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='disciplina',
            field=models.CharField(choices=[('JIUJITSU', 'Jiujitsu'), ('MUAY_THAI', 'Muay Thai'), ('MMA-MUAYTHAI', 'MMA & Muay Thai'), ('MIXTO', 'Mixto')], default='JIUJITSU', max_length=20),
        ),
    ]
