# Generated by Django 5.2.13 on 2026-06-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0006_alter_plan_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='disciplina',
            field=models.CharField(choices=[('JIUJITSU', 'Jiujitsu'), ('MUAY_THAI', 'Muay Thai'), ('MMA_MUAYTHAI', 'MMA & Muay Thai'), ('MIXTO', 'Mixto')], default='JIUJITSU', max_length=20),
        ),
    ]
