# Generated by Django 5.2.13 on 2026-07-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0007_alter_plan_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='clases_asignadas',
        ),
        migrations.AddField(
            model_name='plan',
            name='asistencia_ilimitada',
            field=models.BooleanField(default=False, verbose_name='Asistencia ilimitada'),
        ),
        migrations.AddField(
            model_name='plan',
            name='clases_semana',
            field=models.PositiveIntegerField(default=2, verbose_name='Clases permitidas por semana'),
        ),
        migrations.AddField(
            model_name='plan',
            name='permite_jiu_jitsu',
            field=models.BooleanField(default=False, verbose_name='Incluye Jiu Jitsu'),
        ),
        migrations.AddField(
            model_name='plan',
            name='permite_mma',
            field=models.BooleanField(default=False, verbose_name='Incluye MMA'),
        ),
        migrations.AddField(
            model_name='plan',
            name='permite_muay_thai',
            field=models.BooleanField(default=False, verbose_name='Incluye Muay Thai'),
        ),
    ]
