# Generated by Django 5.2.13 on 2026-07-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0008_remove_plan_disciplina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='detalle_beneficio',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='precio_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('PROGRAMADA', 'Programada'), ('PENDIENTE_PAGO', 'Pendiente de pago'), ('VENCIDA', 'Vencida'), ('SUSPENDIDA', 'Suspendida'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE_PAGO', max_length=20),
        ),
    ]
