# Generated by Django 5.2.13 on 2026-05-18 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLegalEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estudiante', models.CharField(choices=[('ADULTO', 'Adulto'), ('MENOR', 'Menor de edad')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='registros_estudiantes/fotos/')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('contacto_emergencia_nombre', models.CharField(max_length=150)),
                ('contacto_emergencia_celular', models.CharField(max_length=30)),
                ('eps', models.CharField(max_length=150)),
                ('condicion_medica', models.TextField()),
                ('nombre_acudiente', models.CharField(blank=True, max_length=150, null=True)),
                ('documento_acudiente', models.CharField(blank=True, max_length=30, null=True)),
                ('parentesco_acudiente', models.CharField(blank=True, max_length=50, null=True)),
                ('celular_acudiente', models.CharField(blank=True, max_length=30, null=True)),
                ('acepta_reglamento', models.BooleanField(default=False)),
                ('acepta_riesgos', models.BooleanField(default=False)),
                ('autoriza_imagen', models.BooleanField(default=False)),
                ('texto_consentimiento', models.TextField()),
                ('firma_base64', models.TextField()),
                ('fecha_firma', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_firma', models.GenericIPAddressField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE_VALIDACION', 'Pendiente de validación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE_VALIDACION', max_length=30)),
                ('observacion_admin', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro legal de estudiante',
                'verbose_name_plural': 'Registros legales de estudiantes',
                'ordering': ['-creado'],
            },
        ),
    ]
