# Generated by Django 5.2.13 on 2026-06-08 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0005_remove_plan_clases_semanales_plan_clases_mes'),
        ('registros_legales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrolegalestudiante',
            name='plan_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_interesados', to='planes.plan'),
        ),
    ]
