# Generated by Django 5.2.13 on 2026-08-08 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros_legales', '0003_credenciales_elegidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrolegalestudiante',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de diligenciamiento del registro'),
        ),
    ]
