# Generated by Django 5.2.13 on 2026-07-13 12:50

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0002_usuario_debe_cambiar_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username_modificado',
            field=models.BooleanField(default=False, help_text='Indica si ya utilizó su único cambio de nombre de usuario.'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='usuarios_username_unico_sin_mayusculas'),
        ),
    ]
