# Generated by Django 5.2.13 on 2026-04-10 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('disciplina', models.CharField(choices=[('TAEKWONDO', 'Taekwondo'), ('KARATE', 'Karate'), ('JUDO', 'Judo'), ('BOXEO', 'Boxeo'), ('MMA', 'MMA'), ('OTRA', 'Otra')], default='OTRA', max_length=20)),
                ('grado', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_acudiente', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono_acudiente', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PROXIMO_VENCER', 'Próximo a vencer'), ('VENCIDO', 'Vencido'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_alumno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
