# Generated by Django 5.2.13 on 2026-05-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='disciplina',
            field=models.CharField(choices=[('JIU JISTU', 'Jiu Jitsu'), ('MUAY THAI', 'Muay Thai'), ('MMA', 'MMA'), ('OTRA', 'Otra')], default='OTRA', max_length=20),
        ),
    ]
