# Generated by Django 5.2.13 on 2026-05-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('PROXIMO_VENCER', 'Próximo a vencer'), ('VENCIDO', 'Vencido'), ('SUSPENDIDO', 'Suspendido'), ('PENDIENTE', 'Pendiente')], default='ACTIVO', max_length=20),
        ),
    ]
