# Generated by Django 5.2.13 on 2026-07-19 14:25

from django.db import migrations, models


def copiar_datos_acudiente(apps, schema_editor):
    Alumno = apps.get_model('alumnos', 'Alumno')
    Registro = apps.get_model('registros_legales', 'RegistroLegalEstudiante')
    for alumno in Alumno.objects.all().iterator():
        registro = Registro.objects.filter(documento=alumno.documento).order_by('-creado').first()
        if registro:
            alumno.documento_acudiente = registro.documento_acudiente
            alumno.parentesco_acudiente = registro.parentesco_acudiente
            alumno.save(update_fields=['documento_acudiente', 'parentesco_acudiente'])


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alter_alumno_estado'),
        ('registros_legales', '0003_credenciales_elegidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='documento_acudiente',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='parentesco_acudiente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunPython(copiar_datos_acudiente, migrations.RunPython.noop),
    ]
