# Generated by Django 5.2.13 on 2026-08-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alumno_documento_acudiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos/fotos/'),
        ),
    ]
