# Generated by Django 5.2.13 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alumno_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='permitir_asistencia_vencida',
            field=models.BooleanField(
                default=False,
                help_text=(
                    'Excepción individual autorizada por la administración. '
                    'El estudiante seguirá viendo el recordatorio de mora.'
                ),
                verbose_name='Permitir confirmar clases con mensualidad vencida',
            ),
        ),
    ]
